version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:9876 app:app
    ports:
      - 9876:8080
    env_file:
      - ./.env
    depends_on:
      - database
    volumes:
      - .:/usr/share/nginx/html/

  database:
    image: postgres:13
    container_name: postgres_twoge_c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 45s
      retries: 5
      start_period: 30s

volumes:
  postgres_data: